# Generated by Django 4.0.3 on 2022-03-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='DOB',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='PhoneNumber',
            new_name='phone_numbers',
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
