# Generated by Django 4.0.3 on 2022-03-24 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_address_customuser_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='age',
        ),
    ]
